export const ActionTypes = {
    AUTO_COMPLETE: "AUTO_COMPLETE",
    SELECTED_ARTIST: "SELECTED_ARTIST",
    ALBUMS_LIST: "ALBUMS_LIST",
    SELECTED_ALBUM: "SELECTED_ALBUM",
    TRACKS_LIST: "TRACKS_LIST"
  };